apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apple-ingress
  namespace: demo
spec:
  host: apple.apps.ocp4.mclabs.us
  port:
    targetPort: 5678
  to:
    kind: Service
    name: apple-service
